USE seed_races;

INSERT INTO personajes (name, race, subrace, category, origin, role, weapon, damage_type, character_name, morality, threat_level)
VALUES
('Humano', 'Humano', 'Humano común', 'Humanoide', 'The Witcher', 'Cazador de monstruos', 'Espada', 'Cortante', 'Geralt de Rivia', 'Neutral', 'Medio'),
('Elfo', 'Elfo', 'Elfo del Bosque', 'Fey', 'El Señor de los Anillos', 'Arquero', 'Arco', 'Perforante', 'Legolas', 'Bueno', 'Medio'),
('Enano', 'Enano', 'Enano de las Montañas', 'Humanoide', 'El Señor de los Anillos', 'Guerrero', 'Hacha', 'Cortante', 'Gimli', 'Bueno', 'Medio'),
('Orco', 'Orco', 'Orco de Guerra', 'Humanoide', 'Warcraft', 'Jefe de guerra', 'Martillo', 'Contundente', 'Thrall', 'Bueno', 'Alto'),
('Gnomo', 'Gnomo', 'Gnomo del Bosque', 'Fey', 'Warcraft', 'Ingeniero', 'Artilugios', 'Explosivo', 'Gelbin Mekkatorque', 'Bueno', 'Medio'),
('Mediano (Hobbit)', 'Mediano (Hobbit)', 'Hobbit de la Comarca', 'Humanoide', 'El Señor de los Anillos', 'Portador del anillo', 'Daga', 'Cortante', 'Frodo Bolsón', 'Bueno', 'Bajo'),
('Tiflin', 'Tiflin', 'Linaje infernal', 'Humanoide', 'Critical Role', 'Clériga aventurera', 'Maza', 'Sagrado', 'Jester Lavorre', 'Bueno', 'Medio'),
('Aasimar', 'Aasimar', 'Linaje celestial', 'Celestial', 'Baldur''s Gate 3', 'Guerrera sagrada', 'Espada', 'Radiante', 'Dame Aylin', 'Bueno', 'Alto'),
('Drow (Elfo Oscuro)', 'Drow (Elfo Oscuro)', 'Drow de la Infraoscuridad', 'Fey', 'Forgotten Realms', 'Explorador', 'Cimitarra', 'Cortante', 'Drizzt Do''Urden', 'Bueno', 'Alto'),
('Dracónido', 'Dracónido', 'Dracónido guerrero', 'Dracónido', 'Critical Role', 'Paladín oscuro', 'Espada', 'Fuego', 'Arkhan the Cruel', 'Malo', 'Alto'),
('Hada', 'Hada', 'Hada del Bosque', 'Fey', 'Peter Pan', 'Compañera mágica', 'Polvo de hada', 'Arcano', 'Campanita', 'Bueno', 'Bajo'),
('Duende', 'Duende', 'Duende doméstico', 'Fey', 'Harry Potter', 'Ayudante', 'Magia', 'Arcano', 'Dobby', 'Bueno', 'Bajo'),
('Trasgo (Goblin)', 'Trasgo (Goblin)', 'Goblin de clan', 'Humanoide', 'Harry Potter', 'Custodio de tesoros', 'Daga', 'Perforante', 'Griphook', 'Neutral', 'Bajo'),
('Trol', 'Trol', 'Trol de Puente', 'Gigante', 'Harry Potter', 'Bruto', 'Garrote', 'Contundente', 'Trol de Montaña', 'Malo', 'Medio'),
('Ogro', 'Ogro', 'Ogro de Pantano', 'Gigante', 'Shrek', 'Héroe improbable', 'Puños', 'Contundente', 'Shrek', 'Bueno', 'Medio'),
('Gigante', 'Gigante', 'Gigante de las Colinas', 'Gigante', 'The Princess Bride', 'Guardaespaldas', 'Puños', 'Contundente', 'Fezzik', 'Bueno', 'Medio'),
('Liche', 'Liche', 'Hechicero no-muerto', 'No-muerto', 'Dungeons & Dragons', 'Señor de la nigromancia', 'Magia', 'Necrótico', 'Vecna', 'Malo', 'Legendario'),
('Esqueleto', 'Esqueleto', 'Guerrero esqueleto', 'No-muerto', 'He-Man and the Masters of the Universe', 'Tirano', 'Bastón', 'Arcano', 'Skeletor', 'Malo', 'Alto'),
('Zombi', 'Zombi', 'Zombi reanimado', 'No-muerto', 'Plants vs. Zombies', 'Horda', 'Mordida', 'Contundente', 'Zombi (PVZ)', 'Malo', 'Bajo'),
('Vampiro', 'Vampiro', 'Vampiro noble', 'No-muerto', 'Drácula', 'Señor vampírico', 'Colmillos', 'Perforante', 'Conde Drácula', 'Malo', 'Alto'),
('Hombre Lobo', 'Hombre Lobo', 'Licántropo', 'Licántropo', 'Harry Potter', 'Profesor', 'Garras', 'Cortante', 'Remus Lupin', 'Bueno', 'Medio'),
('Ángel', 'Ángel', 'Guardián celestial', 'Celestial', 'Diablo', 'Arcángel guerrero', 'Espada', 'Radiante', 'Tyrael', 'Bueno', 'Alto'),
('Demonio', 'Demonio', 'Demonio mayor', 'Infernal', 'Diablo', 'Señor del terror', 'Garras', 'Fuego', 'Diablo', 'Malo', 'Extremo'),
('Diablillo', 'Diablillo', 'Imp', 'Infernal', 'Doom', 'Hostigador', 'Bola de fuego', 'Fuego', 'Imp (Doom)', 'Malo', 'Medio'),
('Elemental de Fuego', 'Elemental de Fuego', 'Espíritu ígneo', 'Elemental', 'Howl''s Moving Castle', 'Espíritu de fuego', 'Llamas', 'Fuego', 'Calcifer', 'Neutral', 'Medio'),
('Elemental de Agua', 'Elemental de Agua', 'Espíritu acuático', 'Elemental', 'Tales of Symphonia', 'Espíritu guardián', 'Oleada', 'Físico', 'Undine', 'Bueno', 'Medio'),
('Elemental de Aire', 'Elemental de Aire', 'Espíritu del viento', 'Elemental', 'Golden Sun', 'Espíritu del viento', 'Vendaval', 'Físico', 'Gust (Djinn)', 'Bueno', 'Bajo'),
('Elemental de Tierra', 'Elemental de Tierra', 'Espíritu pétreo', 'Elemental', 'Dota 2', 'Coloso viviente', 'Rocas', 'Contundente', 'Tiny', 'Neutral', 'Alto'),
('Sirena/Tritón', 'Sirena/Tritón', 'Habitante del océano', 'Acuático', 'The Little Mermaid', 'Princesa marina', 'Canto', 'Arcano', 'Ariel', 'Bueno', 'Bajo'),
('Nereida', 'Nereida', 'Ninfa marina', 'Acuático', 'Percy Jackson', 'Ninfa del mar', 'Magia marina', 'Arcano', 'Tetis', 'Neutral', 'Medio'),
('Sátiro', 'Sátiro', 'Fey del bosque', 'Fey', 'Percy Jackson', 'Guía', 'Flauta', 'Arcano', 'Grover Underwood', 'Bueno', 'Bajo'),
('Centauro', 'Centauro', 'Centauro guerrero', 'Quimera', 'Percy Jackson', 'Mentor', 'Arco', 'Perforante', 'Quirón', 'Bueno', 'Medio'),
('Minotauro', 'Minotauro', 'Minotauro del laberinto', 'Quimera', 'Hades', 'Guardián', 'Hacha', 'Cortante', 'Asterio', 'Neutral', 'Alto'),
('Cíclope', 'Cíclope', 'Cíclope forjador', 'Gigante', 'La Odisea', 'Pastor brutal', 'Garrote', 'Contundente', 'Polifemo', 'Malo', 'Alto'),
('Arpía', 'Arpía', 'Arpía de los acantilados', 'Quimera', 'God of War', 'Acechador aéreo', 'Garras', 'Cortante', 'Harpía (God of War)', 'Malo', 'Medio'),
('Mantícora', 'Mantícora', 'Bestia del desierto', 'Quimera', 'Heroes of Might and Magic', 'Depredador', 'Aguijón', 'Veneno', 'Manticore (HoMM)', 'Malo', 'Medio'),
('Quimera', 'Quimera', 'Quimera de tres cabezas', 'Quimera', 'Fullmetal Alchemist', 'Criatura trágica', 'Garras', 'Cortante', 'Quimera (Nina)', 'Neutral', 'Bajo'),
('Hidra', 'Hidra', 'Serpiente de muchas cabezas', 'Dracónido', 'Hercules (Disney)', 'Monstruo', 'Múltiples mordidas', 'Perforante', 'Hidra de Lerna', 'Malo', 'Alto'),
('Dragón', 'Dragón', 'Dragón legendario', 'Dracónido', 'El Hobbit', 'Devastador', 'Aliento', 'Fuego', 'Smaug', 'Malo', 'Legendario'),
('Kitsune', 'Kitsune', 'Zorro espiritual', 'Espíritu', 'League of Legends', 'Hechicera', 'Encanto', 'Arcano', 'Ahri', 'Neutral', 'Alto'),
('Oni', 'Oni', 'Oni guerrero', 'Yokai', 'Dead by Daylight', 'Cazador', 'Kanabo', 'Contundente', 'Kazán Yamaoka (The Oni)', 'Malo', 'Alto'),
('Yōkai (genérico)', 'Yōkai (genérico)', 'Espíritu del folclore', 'Yokai', 'Spirited Away', 'Entidad sobrenatural', 'Aura', 'Arcano', 'Sin Rostro', 'Neutral', 'Medio'),
('Sirviente Autómata', 'Sirviente Autómata', 'Autómata menor', 'Constructo', 'Titanfall 2', 'Compañero', 'Brazo mecánico', 'Contundente', 'BT-7274', 'Bueno', 'Alto'),
('Gólem de Piedra', 'Gólem de Piedra', 'Constructo rúnico', 'Constructo', 'Dota 2', 'Guardián', 'Puños', 'Contundente', 'Tiny', 'Neutral', 'Alto'),
('Gólem de Hierro', 'Gólem de Hierro', 'Constructo avanzado', 'Constructo', 'Minecraft', 'Protector', 'Puños', 'Contundente', 'Iron Golem', 'Bueno', 'Medio'),
('Mímico', 'Mímico', 'Devorador camuflado', 'Aberración', 'Dark Souls', 'Depredador', 'Mordida', 'Perforante', 'Mimic (Dark Souls)', 'Malo', 'Alto'),
('Devoramentes', 'Devoramentes', 'Psiónico aberrante', 'Aberración', 'Baldur''s Gate 3', 'Intrigante', 'Psiónica', 'Psíquico', 'The Emperor', 'Neutral', 'Alto'),
('Beholder (Observador)', 'Beholder (Observador)', 'Tirano ocular', 'Aberración', 'Dungeons & Dragons', 'Señor del crimen', 'Rayos oculares', 'Arcano', 'Xanathar', 'Malo', 'Legendario'),
('Súcubo/Íncubo', 'Súcubo/Íncubo', 'Tentador infernal', 'Infernal', 'The Witcher 3', 'Tentador', 'Encanto', 'Oscuro', 'Súcubo (The Witcher 3)', 'Neutral', 'Medio'),
('Driada', 'Driada', 'Ninfa del árbol', 'Fey', 'Mitología griega', 'Guardián del bosque', 'Magia natural', 'Arcano', 'Dafne', 'Bueno', 'Bajo'),
('Ent (Árbol viviente)', 'Ent (Árbol viviente)', 'Guardián ancestral', 'Bestia', 'El Señor de los Anillos', 'Guardián del bosque', 'Puños', 'Contundente', 'Treebeard', 'Bueno', 'Alto'),
('Hombre Lagarto', 'Hombre Lagarto', 'Reptiliano tribal', 'Humanoide', 'The Elder Scrolls V: Skyrim', 'Guerrero', 'Espada', 'Cortante', 'Argoniano (Dragonborn)', 'Neutral', 'Medio'),
('Hombre Pez', 'Hombre Pez', 'Anfibio profundo', 'Humanoide', 'The Shape of Water', 'Superviviente', 'Garras', 'Cortante', 'Amphibian Man', 'Bueno', 'Medio'),
('Hombre Gato', 'Hombre Gato', 'Felino ágil', 'Humanoide', 'DC Comics', 'Ladrona', 'Látigo', 'Cortante', 'Catwoman', 'Neutral', 'Medio'),
('Hombre Rata', 'Hombre Rata', 'Roedor furtivo', 'Humanoide', 'Teenage Mutant Ninja Turtles', 'Mutante maestro', 'Bastón', 'Contundente', 'Splinter', 'Bueno', 'Medio'),
('Hombre Ave (Aarakocra)', 'Hombre Ave (Aarakocra)', 'Aarakocra del viento', 'Humanoide', 'Dungeons & Dragons', 'Explorador aéreo', 'Lanza', 'Perforante', 'Aarakocra (PC clásico)', 'Bueno', 'Medio'),
('Hombre Tábano (Thri-kreen)', 'Hombre Tábano (Thri-kreen)', 'Insectoide del desierto', 'Humanoide', 'Dune', 'Cazador', 'Garras', 'Cortante', 'Fedaykin (inspiración desértica)', 'Neutral', 'Medio'),
('Sombra', 'Sombra', 'Entidad oscura', 'No-muerto', 'The Lord of the Rings: The Two Towers', 'Acechador', 'Energía sombría', 'Oscuro', 'Nazgûl (forma espectral)', 'Malo', 'Alto'),
('Espectro', 'Espectro', 'Espíritu vengativo', 'No-muerto', 'Silent Hill', 'Aparición', 'Toque etéreo', 'Oscuro', 'Pyramid Head (eco de terror)', 'Malo', 'Alto'),
('Banshee', 'Banshee', 'Espíritu del lamento', 'No-muerto', 'Mass Effect', 'Acechador', 'Psiónica', 'Psíquico', 'Banshee (Reaper unit)', 'Malo', 'Alto'),
('Fénix', 'Fénix', 'Ave inmortal', 'Bestia', 'Harry Potter', 'Guardián leal', 'Lágrimas', 'Sagrado', 'Fawkes', 'Bueno', 'Medio'),
('Grifo', 'Grifo', 'Guardián alado', 'Bestia', 'The Witcher 3', 'Depredador', 'Garras', 'Cortante', 'Griffin (The Witcher 3)', 'Neutral', 'Alto'),
('Pegaso', 'Pegaso', 'Corcel alado', 'Bestia', 'Percy Jackson', 'Montura', 'Embiste', 'Contundente', 'Pegasus (Blackjack)', 'Bueno', 'Bajo'),
('Dragón Antiguo', 'Dragón Antiguo', 'Dragón ancestral', 'Dracónido', 'The Elder Scrolls V: Skyrim', 'Señor dracónico', 'Aliento', 'Fuego', 'Alduin', 'Malo', 'Legendario'),
('Dragón del Cielo', 'Dragón del Cielo', 'Dragón aéreo', 'Dracónido', 'Avatar: The Last Airbender', 'Guardián espiritual', 'Aliento', 'Fuego', 'Ran and Shaw', 'Bueno', 'Alto'),
('Dragón del Abismo', 'Dragón del Abismo', 'Dragón profundo', 'Dracónido', 'Dark Souls', 'Devastador', 'Aliento', 'Oscuro', 'Kalameet', 'Malo', 'Legendario'),
('Dragón del Norte', 'Dragón del Norte', 'Dragón de hielo', 'Dracónido', 'Game of Thrones', 'Arma de guerra', 'Aliento', 'Hielo', 'Viserion (no-muerto)', 'Malo', 'Legendario'),
('Hidra Ancestral', 'Hidra Ancestral', 'Hidra primigenia', 'Dracónido', 'Smite', 'Monstruo jefe', 'Múltiples mordidas', 'Perforante', 'Hydra (Smite)', 'Malo', 'Alto'),
('Guardián Dracónido', 'Guardián Dracónido', 'Dracónido custodio', 'Dracónido', 'World of Warcraft', 'Guardián', 'Lanza', 'Perforante', 'Alexstrasza (aspecto dracónico)', 'Bueno', 'Legendario'),
('Bestia Dracónica', 'Bestia Dracónica', 'Híbrido dracónico', 'Dracónido', 'Monster Hunter', 'Depredador', 'Garras', 'Cortante', 'Rathalos', 'Neutral', 'Alto'),
('Dragón Guardián', 'Dragón Guardián', 'Dracónido protector', 'Dracónido', 'The Legend of Zelda: Breath of the Wild', 'Espíritu guardián', 'Aliento', 'Eléctrico', 'Farosh', 'Bueno', 'Legendario'),
('Lobo de las Sombras', 'Lobo de las Sombras', 'Lobo espectral', 'Bestia', 'The Legend of Zelda: Twilight Princess', 'Cazador', 'Colmillos', 'Oscuro', 'Wolf Link', 'Bueno', 'Medio'),
('Bestia del Pantano', 'Bestia del Pantano', 'Criatura anfibia', 'Bestia', 'Resident Evil 4', 'Acechador', 'Mordida', 'Perforante', 'Del Lago', 'Malo', 'Alto'),
('Acechador del Bosque', 'Acechador del Bosque', 'Depredador forestal', 'Bestia', 'Predator', 'Cazador', 'Cuchillas', 'Cortante', 'Yautja (Predator)', 'Malo', 'Alto'),
('Depredador del Desierto', 'Depredador del Desierto', 'Cazador del yermo', 'Bestia', 'Dune', 'Depredador', 'Mordida', 'Perforante', 'Sandworm (Shai-Hulud)', 'Neutral', 'Legendario'),
('Bestia de las Nieves', 'Bestia de las Nieves', 'Criatura ártica', 'Bestia', 'Frozen', 'Guardián', 'Garras', 'Hielo', 'Marshmallow', 'Neutral', 'Medio'),
('Cazador Nocturno', 'Cazador Nocturno', 'Bestia sigilosa', 'Bestia', 'Bloodborne', 'Cazador', 'Garras', 'Cortante', 'Beast (Scourge)', 'Malo', 'Alto'),
('Bestia Cornuda', 'Bestia Cornuda', 'Bestia salvaje', 'Bestia', 'World of Warcraft', 'Destructor', 'Cuernos', 'Contundente', 'The Beast (Blackrock Spire)', 'Malo', 'Alto'),
('Bestia Alada', 'Bestia Alada', 'Depredador aéreo', 'Bestia', 'How to Train Your Dragon', 'Compañero', 'Aliento', 'Fuego', 'Toothless', 'Bueno', 'Alto'),
('Bestia del Valle', 'Bestia del Valle', 'Bestia territorial', 'Bestia', 'The Hobbit: An Unexpected Journey', 'Depredador', 'Mordida', 'Perforante', 'Warg', 'Malo', 'Medio'),
('Kraken', 'Kraken', 'Titán marino', 'Acuático', 'Clash of the Titans', 'Destructor', 'Tentáculos', 'Contundente', 'Kraken', 'Malo', 'Legendario'),
('Leviatán', 'Leviatán', 'Ser primordial marino', 'Acuático', 'Supernatural', 'Entidad antigua', 'Maldición', 'Oscuro', 'Leviathans', 'Malo', 'Legendario'),
('Serpiente Marina', 'Serpiente Marina', 'Serpiente colosal', 'Acuático', 'One Piece', 'Monstruo marino', 'Constricción', 'Contundente', 'Sea King', 'Neutral', 'Alto'),
('Monstruo Marino', 'Monstruo Marino', 'Criatura oceánica', 'Acuático', 'Pacific Rim', 'Kaiju', 'Garras', 'Cortante', 'Knifehead', 'Malo', 'Legendario'),
('Bestia Abisal', 'Bestia Abisal', 'Criatura de las profundidades', 'Acuático', 'Subnautica', 'Depredador ápice', 'Mordida', 'Perforante', 'Reaper Leviathan', 'Neutral', 'Legendario'),
('Guardián del Mar', 'Guardián del Mar', 'Protector oceánico', 'Acuático', 'Moana', 'Guardián', 'Agua', 'Físico', 'Te Fiti', 'Bueno', 'Legendario'),
('Criatura del Arrecife', 'Criatura del Arrecife', 'Habitante coralino', 'Acuático', 'Finding Nemo', 'Habitante del arrecife', 'Espinas', 'Perforante', 'Bloat (pez globo)', 'Bueno', 'Bajo'),
('Acechador Marino', 'Acechador Marino', 'Cazador oceánico', 'Acuático', 'Jaws', 'Depredador', 'Mordida', 'Perforante', 'Tiburón (Jaws)', 'Neutral', 'Alto'),
('Valquiria', 'Valquiria', 'Guerrera del Valhalla', 'Celestial', 'God of War', 'Jefa guerrera', 'Lanza', 'Sagrado', 'Sigrun', 'Neutral', 'Legendario'),
('Arcángel', 'Arcángel', 'General celestial', 'Celestial', 'Supernatural', 'Comandante', 'Espada angelical', 'Radiante', 'Michael', 'Neutral', 'Legendario'),
('Querubín', 'Querubín', 'Custodio divino', 'Celestial', 'Bayonetta', 'Custodio', 'Luz divina', 'Radiante', 'Affinity (ángel)', 'Malo', 'Medio'),
('Serafín', 'Serafín', 'Ángel ígneo', 'Celestial', 'Diablo III', 'Juez del cielo', 'Llamas sagradas', 'Fuego', 'Imperius', 'Neutral', 'Legendario'),
('Guardián Celestial', 'Guardián Celestial', 'Protector divino', 'Celestial', 'Overwatch', 'Sanador', 'Bastón caduceo', 'Sagrado', 'Mercy', 'Bueno', 'Medio'),
('Mensajero Divino', 'Mensajero Divino', 'Heraldo celestial', 'Celestial', 'Hades', 'Mensajero', 'Talaria', 'Físico', 'Hermes', 'Neutral', 'Alto'),
('Centinela Celestial', 'Centinela Celestial', 'Vigía eterno', 'Celestial', 'Destiny 2', 'Guardián', 'Rifle', 'Energía', 'The Guardian', 'Bueno', 'Alto'),
('Fantasma Errante', 'Fantasma Errante', 'Espíritu sin descanso', 'No-muerto', 'The Sixth Sense', 'Aparición', 'Presencia', 'Oscuro', 'Ghost (Sixth Sense)', 'Neutral', 'Bajo'),
('Guardián de la Cripta', 'Guardián de la Cripta', 'No-muerto custodio', 'No-muerto', 'Castlevania', 'Guardián', 'Hacha', 'Cortante', 'Death', 'Malo', 'Legendario'),
('Espíritu Errante', 'Espíritu Errante', 'Alma perdida', 'No-muerto', 'Ghost Rider', 'Alma en pena', 'Cadena', 'Fuego', 'Ghost Rider', 'Bueno', 'Alto'),
('Sombra Antigua', 'Sombra Antigua', 'Entidad ancestral', 'No-muerto', 'Doctor Who', 'Entidad', 'Sombra', 'Oscuro', 'Vashta Nerada', 'Neutral', 'Alto'),
('Entidad Fantasmal', 'Entidad Fantasmal', 'Espectro poderoso', 'No-muerto', 'The Conjuring', 'Aparición', 'Maldición', 'Oscuro', 'Bathsheba Sherman', 'Malo', 'Alto'),
('Vigilante de la Tumba', 'Vigilante de la Tumba', 'Centinela no-muerto', 'No-muerto', 'Dark Souls', 'Guardián', 'Espada', 'Cortante', 'Grave Warden', 'Malo', 'Alto'),
('Aparición Nocturna', 'Aparición Nocturna', 'Espíritu nocturno', 'No-muerto', 'The Witcher', 'Acechador', 'Garras etéreas', 'Oscuro', 'Nightwraith', 'Malo', 'Alto'),
('Titán Antiguo', 'Titán Antiguo', 'Titán primordial', 'Gigante', 'Attack on Titan', 'Destructor', 'Puños', 'Contundente', 'Founding Titan', 'Neutral', 'Legendario'),
('Coloso Errante', 'Coloso Errante', 'Gigante colosal', 'Gigante', 'Shadow of the Colossus', 'Errante', 'Puños', 'Contundente', 'Valus', 'Neutral', 'Legendario'),
('Guardián de las Montañas', 'Guardián de las Montañas', 'Gigante pétreo', 'Gigante', 'God of War', 'Protector', 'Rocas', 'Contundente', 'Stone Guardian', 'Neutral', 'Alto'),
('Gigante Errante', 'Gigante Errante', 'Gigante nómada', 'Gigante', 'Skyrim', 'Viajero', 'Garrote', 'Contundente', 'Giant', 'Neutral', 'Alto'),
('Señor Infernal', 'Señor Infernal', 'Archidemonio', 'Infernal', 'Diablo IV', 'Gobernante', 'Garras', 'Fuego', 'Mephisto', 'Malo', 'Legendario'),
('Acechador Infernal', 'Acechador Infernal', 'Cazador demoníaco', 'Infernal', 'DOOM Eternal', 'Cazador', 'Garras', 'Fuego', 'Marauder', 'Malo', 'Alto'),
('Bestia Infernal', 'Bestia Infernal', 'Criatura del inframundo', 'Infernal', 'Hellboy', 'Destructor', 'Colmillos', 'Fuego', 'Sammael', 'Malo', 'Alto'),
('Guardián del Inframundo', 'Guardián del Inframundo', 'Custodio infernal', 'Infernal', 'Hades', 'Guardián', 'Lanza', 'Fuego', 'Hades', 'Neutral', 'Legendario'),
('Entidad del Caos', 'Entidad del Caos', 'Manifestación caótica', 'Infernal', 'Warhammer 40K', 'Desestabilizador', 'Energía caótica', 'Oscuro', 'Chaos Daemon', 'Malo', 'Legendario'),
('Centauro de Guerra', 'Centauro de Guerra', 'Centauro veterano', 'Quimera', 'Total War: Troy', 'Guerrero', 'Lanza', 'Perforante', 'Centaur Champion', 'Neutral', 'Alto'),
('Minotauro Antiguo', 'Minotauro Antiguo', 'Minotauro ancestral', 'Quimera', 'Assassin’s Creed Odyssey', 'Guardián', 'Hacha', 'Cortante', 'Minotaur of Crete', 'Malo', 'Alto'),
('Quimera Salvaje', 'Quimera Salvaje', 'Quimera indómita', 'Quimera', 'Monster Hunter', 'Bestia', 'Aliento', 'Fuego', 'Teostra', 'Neutral', 'Alto'),
('Arpía del Viento', 'Arpía del Viento', 'Arpía aérea', 'Quimera', 'Hades', 'Hostigador', 'Garras', 'Cortante', 'Harpies', 'Neutral', 'Medio'),
('Mantícora Oscura', 'Mantícora Oscura', 'Mantícora corrupta', 'Quimera', 'Dragon Age', 'Depredador', 'Aguijón', 'Veneno', 'Manticore', 'Malo', 'Alto'),
('Espíritu del Bosque', 'Espíritu del Bosque', 'Entidad natural', 'Espíritu', 'Princess Mononoke', 'Protector', 'Magia natural', 'Arcano', 'Forest Spirit', 'Bueno', 'Alto'),
('Espíritu del Lago', 'Espíritu del Lago', 'Entidad acuática', 'Espíritu', 'The Witcher', 'Guardián', 'Magia', 'Arcano', 'Lady of the Lake', 'Bueno', 'Alto'),
('Espíritu Ancestral', 'Espíritu Ancestral', 'Espíritu primigenio', 'Espíritu', 'Avatar', 'Consejero', 'Energía espiritual', 'Arcano', 'Raava', 'Bueno', 'Legendario'),
('Espíritu Guardián', 'Espíritu Guardián', 'Protector espiritual', 'Espíritu', 'Sekiro', 'Guardián', 'Energía espiritual', 'Arcano', 'Divine Dragon', 'Bueno', 'Legendario'),
('Centinela de Acero', 'Centinela de Acero', 'Autómata bélico', 'Constructo', 'Horizon Zero Dawn', 'Vigía', 'Lanza', 'Perforante', 'Watcher', 'Neutral', 'Alto'),
('Autómata Antiguo', 'Autómata Antiguo', 'Máquina arcaica', 'Constructo', 'NieR: Automata', 'Guardián', 'Puños', 'Contundente', 'Goliath', 'Neutral', 'Legendario'),
('Guardián Mecánico', 'Guardián Mecánico', 'Constructo armado', 'Constructo', 'Bioshock', 'Defensor', 'Taladro', 'Perforante', 'Big Daddy', 'Neutral', 'Alto'),
('Horror de las Profundidades', 'Horror de las Profundidades', 'Aberración abisal', 'Aberración', 'Lovecraft Country', 'Terror', 'Tentáculos', 'Contundente', 'Deep One', 'Malo', 'Alto'),
('Entidad Incomprensible', 'Entidad Incomprensible', 'Ser cósmico', 'Aberración', 'Call of Cthulhu', 'Desestabilizador', 'Psiónica', 'Psíquico', 'Cthulhu', 'Malo', 'Legendario'),
('Acechador Mental', 'Acechador Mental', 'Psiónico', 'Aberración', 'XCOM', 'Controlador', 'Psiónica', 'Psíquico', 'Sectoid', 'Malo', 'Alto'),
('Observador Antiguo', 'Observador Antiguo', 'Vigilante cósmico', 'Aberración', 'Doctor Strange', 'Observador', 'Rayos mentales', 'Psíquico', 'Dormammu', 'Malo', 'Legendario'),
('Gárgola', 'Gárgola', 'Estatua alada', 'Quimera', 'Gargoyles', 'Guardián', 'Garras', 'Cortante', 'Goliath', 'Bueno', 'Alto'),
('Basilisco', 'Basilisco', 'Ser reptiliano', 'Bestia', 'Harry Potter', 'Depredador', 'Mirada', 'Petrificación', 'Basilisk of Salazar', 'Malo', 'Legendario'),
('Cocatriz', 'Cocatriz', 'Ave reptiliana', 'Bestia', 'The Witcher', 'Depredador', 'Picotazo', 'Veneno', 'Cockatrice', 'Neutral', 'Alto'),
('Quimera Marina', 'Quimera Marina', 'Híbrido marino', 'Quimera', 'Assassin’s Creed Odyssey', 'Depredador', 'Mordida', 'Perforante', 'Sea Chimera', 'Malo', 'Alto'),
('Escila', 'Escila', 'Monstruo marino', 'Acuático', 'God of War', 'Destructor costero', 'Tentáculos', 'Contundente', 'Scylla', 'Malo', 'Legendario'),
('Caribdis', 'Caribdis', 'Entidad oceánica', 'Acuático', 'La Odisea', 'Engullidor', 'Remolino', 'Físico', 'Charybdis', 'Neutral', 'Legendario'),
('Hipogrifo', 'Hipogrifo', 'Híbrido alado', 'Quimera', 'Harry Potter', 'Montura', 'Garras', 'Cortante', 'Buckbeak', 'Bueno', 'Medio'),
('Cerbero', 'Cerbero', 'Can infernal', 'Bestia', 'Hades', 'Guardián', 'Mordidas', 'Perforante', 'Cerberus', 'Bueno', 'Legendario'),
('Medusa', 'Medusa', 'Gorgona', 'Humanoide', 'Clash of the Titans', 'Acechadora', 'Mirada', 'Petrificación', 'Medusa', 'Malo', 'Alto'),
('Hecatónquiro', 'Hecatónquiro', 'Gigante de cien brazos', 'Gigante', 'God of War', 'Destructor', 'Puños', 'Contundente', 'Hecatoncheires', 'Malo', 'Legendario'),
('Araña Gigante', 'Araña Gigante', 'Arácnido colosal', 'Bestia', 'Skyrim', 'Depredador', 'Colmillos', 'Veneno', 'Frostbite Spider', 'Neutral', 'Alto'),
('Serpiente Gigante', 'Serpiente Gigante', 'Reptil colosal', 'Bestia', 'Dark Souls', 'Constricción', 'Cuerpo', 'Contundente', 'Primordial Serpent', 'Neutral', 'Legendario'),
('Escorpión Gigante', 'Escorpión Gigante', 'Artrópodo colosal', 'Bestia', 'Fallout', 'Depredador', 'Aguijón', 'Veneno', 'Radscorpion', 'Malo', 'Alto'),
('Gusano de Arena', 'Gusano de Arena', 'Anélido colosal', 'Bestia', 'Dune', 'Depredador subterráneo', 'Mordida', 'Perforante', 'Shai-Hulud', 'Neutral', 'Legendario'),
('Cangrejo Gigante', 'Cangrejo Gigante', 'Crustáceo colosal', 'Acuático', 'Elden Ring', 'Defensor', 'Pinzas', 'Contundente', 'Giant Crab', 'Neutral', 'Alto'),
('Calamar Gigante', 'Calamar Gigante', 'Cefalópodo colosal', 'Acuático', 'Pirates of the Caribbean', 'Depredador', 'Tentáculos', 'Contundente', 'Kraken', 'Malo', 'Legendario'),
('Escarabajo Gigante', 'Escarabajo Gigante', 'Insecto colosal', 'Bestia', 'Hollow Knight', 'Embiste', 'Caparazón', 'Contundente', 'Giant Husk', 'Neutral', 'Medio'),
('Titán de Piedra', 'Titán de Piedra', 'Gigante pétreo', 'Gigante', 'God of War', 'Guardián', 'Puños', 'Contundente', 'Stone Titan', 'Neutral', 'Legendario'),
('Titán de Hielo', 'Titán de Hielo', 'Gigante ártico', 'Gigante', 'Skyrim', 'Depredador', 'Puños', 'Hielo', 'Frost Giant', 'Neutral', 'Alto'),
('Titán de Fuego', 'Titán de Fuego', 'Gigante ígneo', 'Gigante', 'Dark Souls', 'Destructor', 'Puños', 'Fuego', 'Fire Giant', 'Malo', 'Legendario'),
('Coloso de Hierro', 'Coloso de Hierro', 'Autómata colosal', 'Constructo', 'Shadow of the Colossus', 'Guardián', 'Puños', 'Contundente', 'Iron Colossus', 'Neutral', 'Legendario'),
('Coloso de Obsidiana', 'Coloso de Obsidiana', 'Gigante volcánico', 'Constructo', 'Shadow of the Colossus', 'Defensor', 'Puños', 'Cortante', 'Obsidian Colossus', 'Neutral', 'Legendario'),
('Coloso Viviente', 'Coloso Viviente', 'Gigante animado', 'Gigante', 'Shadow of the Colossus', 'Errante', 'Puños', 'Contundente', 'Living Colossus', 'Neutral', 'Legendario');